### PR TITLE
Fix messages

### PR DESCRIPTION
**Pull request by jonathanhecl**
Fix messages

### CODE REVIEW

**Comment by matiascalegaris** [comment]
Hello, thanks for your work

please before doing a commit run git_ignore_case.sh and commit only the changes, its really hard to  perform review with al the changes performed by the editor

**Review by RecoX — APPROVED** [review]
For next time before commit use the file `git_ignore_case`

@matiascalegaris this are the changes proposed.

```
        If dir(ObjFile, vbArchive) = "" Then
            MsgBox "Error inicializando Proyectiles.", vbCritical + vbOKOnly
            End
        End If
```

**Review by matiascalegaris — CHANGES_REQUESTED** [review]
please remove al changes for case performed by vb editor so we can avoid conflict with another branch and perform better reviews

**Review by RecoX — CHANGES_REQUESTED** [review]
please remove al changes for case performed by vb editor so we can avoid conflict with another branch and perform better reviews

**Pull request closed without merging**
